
package org.talend.esb.sample.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1
 * Mon Jan 24 17:51:18 EET 2011
 * Generated source version: 2.3.1
 */

@XmlRootElement(name = "greetMe", namespace = "http://talend.org/esb/examples/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "greetMe", namespace = "http://talend.org/esb/examples/")

public class GreetMe {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

