
package org.talend.esb.sample.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1
 * Mon Jan 24 17:51:18 EET 2011
 * Generated source version: 2.3.1
 */

@XmlRootElement(name = "greetMeResponse", namespace = "http://talend.org/esb/examples/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "greetMeResponse", namespace = "http://talend.org/esb/examples/")

public class GreetMeResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

