
package org.sopera.services.reservationservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.0-SNAPSHOT
 * 2011-01-17T11:54:21.955+02:00
 * Generated source version: 2.4.0-SNAPSHOT
 * 
 */
 
public class ReservationService_Localhost_Server{

    protected ReservationService_Localhost_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ReservationServiceImpl();
        String address = "http://localhost:8888/soap/ReservationServiceProvider/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ReservationService_Localhost_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
