package org.sopera.services.reservationservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.0-SNAPSHOT
 * 2011-01-17T11:54:21.949+02:00
 * Generated source version: 2.4.0-SNAPSHOT
 * 
 */
 
@WebService(targetNamespace = "http://services.sopera.org/ReservationService", name = "ReservationService")
@XmlSeeAlso({org.sopera.services.reservation.types.ObjectFactory.class, org.sopera.services.crm.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ReservationService {

    @WebResult(name = "Confirmation", targetNamespace = "http://services.sopera.org/reservation/types", partName = "body")
    @WebMethod(action = "getConfirmationOfReservation")
    public org.sopera.services.reservation.types.ConfirmationType getConfirmationOfReservation(
        @WebParam(partName = "body", name = "ReservationToConfirm", targetNamespace = "http://services.sopera.org/reservation/types")
        org.sopera.services.reservation.types.ReservationType body
    );

    @WebResult(name = "ReservationStatus", targetNamespace = "http://services.sopera.org/reservation/types", partName = "body")
    @WebMethod(action = "submitCarReservation")
    public org.sopera.services.reservation.types.RESStatusType submitCarReservation(
        @WebParam(partName = "body", name = "Reservation", targetNamespace = "http://services.sopera.org/reservation/types")
        org.sopera.services.reservation.types.ReservationType body
    );

    @WebResult(name = "RESCarList", targetNamespace = "http://services.sopera.org/reservation/types", partName = "body")
    @WebMethod(action = "getAvailableCars")
    public org.sopera.services.reservation.types.RESCarListType getAvailableCars(
        @WebParam(partName = "body", name = "RESProfile", targetNamespace = "http://services.sopera.org/reservation/types")
        org.sopera.services.reservation.types.RESProfileType body
    );
}
