
package org.sopera.services.reservationservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.sopera.services.reservationservice.ReservationService;
import org.sopera.services.reservationservice.ReservationServiceProvider;

/**
 * This class was generated by Apache CXF 2.4.0-SNAPSHOT
 * 2011-01-17T11:54:25.354+02:00
 * Generated source version: 2.4.0-SNAPSHOT
 * 
 */
public final class ReservationService_Localhost_Client {

    private static final QName SERVICE_NAME = new QName("http://services.sopera.org/ReservationService", "ReservationServiceProvider");

    private ReservationService_Localhost_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ReservationServiceProvider.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ReservationServiceProvider ss = new ReservationServiceProvider(wsdlURL, SERVICE_NAME);
        ReservationService port = ss.getLocalhost();  
        
        {
        System.out.println("Invoking getConfirmationOfReservation...");
        org.sopera.services.reservation.types.ReservationType _getConfirmationOfReservation_body = null;
        org.sopera.services.reservation.types.ConfirmationType _getConfirmationOfReservation__return = port.getConfirmationOfReservation(_getConfirmationOfReservation_body);
        System.out.println("getConfirmationOfReservation.result=" + _getConfirmationOfReservation__return);


        }
        {
        System.out.println("Invoking submitCarReservation...");
        org.sopera.services.reservation.types.ReservationType _submitCarReservation_body = null;
        org.sopera.services.reservation.types.RESStatusType _submitCarReservation__return = port.submitCarReservation(_submitCarReservation_body);
        System.out.println("submitCarReservation.result=" + _submitCarReservation__return);


        }
        {
        System.out.println("Invoking getAvailableCars...");
        org.sopera.services.reservation.types.RESProfileType _getAvailableCars_body = null;
        org.sopera.services.reservation.types.RESCarListType _getAvailableCars__return = port.getAvailableCars(_getAvailableCars_body);
        System.out.println("getAvailableCars.result=" + _getAvailableCars__return);


        }

        System.exit(0);
    }

}
