
package org.sopera.services.crmservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.sopera.services.crmservice.CRMService;
import org.sopera.services.crmservice.CRMServiceProvider;

/**
 * This class was generated by Apache CXF 2.4.0-SNAPSHOT
 * 2011-01-17T11:54:18.399+02:00
 * Generated source version: 2.4.0-SNAPSHOT
 * 
 */
public final class CRMService_Localhost_Client {

    private static final QName SERVICE_NAME = new QName("http://services.sopera.org/CRMService", "CRMServiceProvider");

    private CRMService_Localhost_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CRMServiceProvider.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CRMServiceProvider ss = new CRMServiceProvider(wsdlURL, SERVICE_NAME);
        CRMService port = ss.getLocalhost();  
        
        {
        System.out.println("Invoking getCRMStatus...");
        org.sopera.services.crm.types.CustomerDetailsType _getCRMStatus_body = null;
        org.sopera.services.crm.types.RYLCStatusType _getCRMStatus__return = port.getCRMStatus(_getCRMStatus_body);
        System.out.println("getCRMStatus.result=" + _getCRMStatus__return);


        }
        {
        System.out.println("Invoking getCRMInformation...");
        org.sopera.services.crm.types.LoginUserType _getCRMInformation_body = null;
        org.sopera.services.crm.types.CustomerDetailsType _getCRMInformation__return = port.getCRMInformation(_getCRMInformation_body);
        System.out.println("getCRMInformation.result=" + _getCRMInformation__return);


        }
        {
        System.out.println("Invoking updateCRMStatus...");
        org.sopera.services.crm.types.RYLCStatusType _updateCRMStatus_body = null;
        port.updateCRMStatus(_updateCRMStatus_body);


        }

        System.exit(0);
    }

}
