
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.sopera.services.reservationservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.0-SNAPSHOT
 * 2011-01-17T11:54:25.408+02:00
 * Generated source version: 2.4.0-SNAPSHOT
 * 
 */

@javax.jws.WebService(
                      serviceName = "ReservationServiceProvider",
                      portName = "localhost",
                      targetNamespace = "http://services.sopera.org/ReservationService",
                      wsdlLocation = "ReservationService.wsdl",
                      endpointInterface = "org.sopera.services.reservationservice.ReservationService")
                      
public class ReservationServiceImpl implements ReservationService {

    private static final Logger LOG = Logger.getLogger(ReservationServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.sopera.services.reservationservice.ReservationService#getConfirmationOfReservation(org.sopera.services.reservation.types.ReservationType  body )*
     */
    public org.sopera.services.reservation.types.ConfirmationType getConfirmationOfReservation(org.sopera.services.reservation.types.ReservationType body) { 
        LOG.info("Executing operation getConfirmationOfReservation");
        System.out.println(body);
        try {
            org.sopera.services.reservation.types.ConfirmationType _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.sopera.services.reservationservice.ReservationService#submitCarReservation(org.sopera.services.reservation.types.ReservationType  body )*
     */
    public org.sopera.services.reservation.types.RESStatusType submitCarReservation(org.sopera.services.reservation.types.ReservationType body) { 
        LOG.info("Executing operation submitCarReservation");
        System.out.println(body);
        try {
            org.sopera.services.reservation.types.RESStatusType _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.sopera.services.reservationservice.ReservationService#getAvailableCars(org.sopera.services.reservation.types.RESProfileType  body )*
     */
    public org.sopera.services.reservation.types.RESCarListType getAvailableCars(org.sopera.services.reservation.types.RESProfileType body) { 
        LOG.info("Executing operation getAvailableCars");
        System.out.println(body);
        try {
            org.sopera.services.reservation.types.RESCarListType _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
