
/*
 * 
 */

package org.sopera.services.reservationservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0-SNAPSHOT
 * 2011-01-17T11:54:25.427+02:00
 * Generated source version: 2.4.0-SNAPSHOT
 * 
 */


@WebServiceClient(name = "ReservationServiceProvider", 
                  wsdlLocation = "ReservationService.wsdl",
                  targetNamespace = "http://services.sopera.org/ReservationService") 
public class ReservationServiceProvider extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.sopera.org/ReservationService", "ReservationServiceProvider");
    public final static QName Localhost = new QName("http://services.sopera.org/ReservationService", "localhost");
    static {
        URL url = null;
        try {
            url = new URL("ReservationService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from ReservationService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ReservationServiceProvider(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReservationServiceProvider(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationServiceProvider() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ReservationServiceProvider(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ReservationServiceProvider(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ReservationServiceProvider(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReservationService
     */
    @WebEndpoint(name = "localhost")
    public ReservationService getLocalhost() {
        return super.getPort(Localhost, ReservationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservationService
     */
    @WebEndpoint(name = "localhost")
    public ReservationService getLocalhost(WebServiceFeature... features) {
        return super.getPort(Localhost, ReservationService.class, features);
    }

}
