
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.sopera.services.crmservice;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.0-SNAPSHOT
 * 2011-01-17T11:54:18.458+02:00
 * Generated source version: 2.4.0-SNAPSHOT
 * 
 */

@javax.jws.WebService(
                      serviceName = "CRMServiceProvider",
                      portName = "localhost",
                      targetNamespace = "http://services.sopera.org/CRMService",
                      wsdlLocation = "CRMService.wsdl",
                      endpointInterface = "org.sopera.services.crmservice.CRMService")
                      
public class CRMServiceImpl implements CRMService {

    private static final Logger LOG = Logger.getLogger(CRMServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.sopera.services.crmservice.CRMService#getCRMStatus(org.sopera.services.crm.types.CustomerDetailsType  body )*
     */
    public org.sopera.services.crm.types.RYLCStatusType getCRMStatus(org.sopera.services.crm.types.CustomerDetailsType body) { 
        LOG.info("Executing operation getCRMStatus");
        System.out.println(body);
        try {
            org.sopera.services.crm.types.RYLCStatusType _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.sopera.services.crmservice.CRMService#getCRMInformation(org.sopera.services.crm.types.LoginUserType  body )*
     */
    public org.sopera.services.crm.types.CustomerDetailsType getCRMInformation(org.sopera.services.crm.types.LoginUserType body) { 
        LOG.info("Executing operation getCRMInformation");
        System.out.println(body);
        try {
            org.sopera.services.crm.types.CustomerDetailsType _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.sopera.services.crmservice.CRMService#updateCRMStatus(org.sopera.services.crm.types.RYLCStatusType  body )*
     */
    public void updateCRMStatus(org.sopera.services.crm.types.RYLCStatusType body) { 
        LOG.info("Executing operation updateCRMStatus");
        System.out.println(body);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
