package org.sopera.services.crmservice;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.0-SNAPSHOT
 * 2011-01-17T11:54:18.470+02:00
 * Generated source version: 2.4.0-SNAPSHOT
 * 
 */
 
@WebService(targetNamespace = "http://services.sopera.org/CRMService", name = "CRMService")
@XmlSeeAlso({org.sopera.services.crm.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CRMService {

    @WebResult(name = "RYLCStatus", targetNamespace = "http://services.sopera.org/crm/types", partName = "body")
    @WebMethod(action = "getCRMStatus")
    public org.sopera.services.crm.types.RYLCStatusType getCRMStatus(
        @WebParam(partName = "body", name = "CustomerDetails", targetNamespace = "http://services.sopera.org/crm/types")
        org.sopera.services.crm.types.CustomerDetailsType body
    );

    @WebResult(name = "CustomerDetails", targetNamespace = "http://services.sopera.org/crm/types", partName = "body")
    @WebMethod(action = "getCRMInformation")
    public org.sopera.services.crm.types.CustomerDetailsType getCRMInformation(
        @WebParam(partName = "body", name = "LoginUser", targetNamespace = "http://services.sopera.org/crm/types")
        org.sopera.services.crm.types.LoginUserType body
    );

    @Oneway
    @WebMethod(action = "updateCRMStatus")
    public void updateCRMStatus(
        @WebParam(partName = "body", name = "RYLCStatus", targetNamespace = "http://services.sopera.org/crm/types")
        org.sopera.services.crm.types.RYLCStatusType body
    );
}
