
package org.oasis_open.docs.ws_sx.ws_trust._200512.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue Dec 28 16:52:06 EET 2010
 * Generated source version: 2.3.1
 * 
 */

public final class SecurityTokenResponseService_SecurityTokenServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl/", "SecurityTokenServiceProvider");

    private SecurityTokenResponseService_SecurityTokenServiceSOAP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SecurityTokenServiceProvider.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SecurityTokenServiceProvider ss = new SecurityTokenServiceProvider(wsdlURL, SERVICE_NAME);
        SecurityTokenResponseService port = ss.getSecurityTokenServiceSOAP();  
        
        {
        System.out.println("Invoking requestSecurityTokenResponse...");
        org.oasis_open.docs.ws_sx.ws_trust._200512.RequestSecurityTokenResponseType _requestSecurityTokenResponse_response = null;
        port.requestSecurityTokenResponse(_requestSecurityTokenResponse_response);


        }

        System.exit(0);
    }

}
