
/*
 * 
 */

package org.oasis_open.docs.ws_sx.ws_trust._200512.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue Dec 28 16:52:07 EET 2010
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "SecurityTokenServiceProvider", 
                  wsdlLocation = "file:/D:/WORK_SOPERA/ws-trust/ws-trust-1.4.wsdl",
                  targetNamespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl/") 
public class SecurityTokenServiceProvider extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl/", "SecurityTokenServiceProvider");
    public final static QName SecurityTokenServiceSOAP = new QName("http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl/", "SecurityTokenServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/WORK_SOPERA/ws-trust/ws-trust-1.4.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/D:/WORK_SOPERA/ws-trust/ws-trust-1.4.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SecurityTokenServiceProvider(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SecurityTokenServiceProvider(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecurityTokenServiceProvider() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SecurityTokenServiceProvider(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public SecurityTokenServiceProvider(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public SecurityTokenServiceProvider(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SecurityTokenResponseService
     */
    @WebEndpoint(name = "SecurityTokenServiceSOAP")
    public SecurityTokenResponseService getSecurityTokenServiceSOAP() {
        return super.getPort(SecurityTokenServiceSOAP, SecurityTokenResponseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecurityTokenResponseService
     */
    @WebEndpoint(name = "SecurityTokenServiceSOAP")
    public SecurityTokenResponseService getSecurityTokenServiceSOAP(WebServiceFeature... features) {
        return super.getPort(SecurityTokenServiceSOAP, SecurityTokenResponseService.class, features);
    }

}
