
package org.oasis_open.docs.ws_sx.ws_trust._200512.wsdl;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue Dec 28 16:52:07 EET 2010
 * Generated source version: 2.3.1
 * 
 */
 
public class SecurityTokenResponseService_SecurityTokenServiceSOAP_Server{

    protected SecurityTokenResponseService_SecurityTokenServiceSOAP_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new SecurityTokenResponseServiceImpl();
        String address = "http://localhost:18080/SecurityTokenServiceProvider/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new SecurityTokenResponseService_SecurityTokenServiceSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
