
/*
 * 
 */

package org.oasis_open.docs.ws_sx.ws_trust._200512.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0-SNAPSHOT
 * 2011-01-06T10:25:02.246+02:00
 * Generated source version: 2.4.0-SNAPSHOT
 * 
 */


@WebServiceClient(name = "SecurityTokenServiceProvider", 
                  wsdlLocation = "ws-trust-1.4-service.wsdl",
                  targetNamespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl") 
public class SecurityTokenServiceProvider extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl", "SecurityTokenServiceProvider");
    public final static QName SecurityTokenServiceSOAP = new QName("http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl", "SecurityTokenServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("ws-trust-1.4-service.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from ws-trust-1.4-service.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SecurityTokenServiceProvider(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SecurityTokenServiceProvider(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecurityTokenServiceProvider() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SecurityTokenServiceProvider(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SecurityTokenServiceProvider(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SecurityTokenServiceProvider(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SecurityTokenService
     */
    @WebEndpoint(name = "SecurityTokenServiceSOAP")
    public SecurityTokenService getSecurityTokenServiceSOAP() {
        return super.getPort(SecurityTokenServiceSOAP, SecurityTokenService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecurityTokenService
     */
    @WebEndpoint(name = "SecurityTokenServiceSOAP")
    public SecurityTokenService getSecurityTokenServiceSOAP(WebServiceFeature... features) {
        return super.getPort(SecurityTokenServiceSOAP, SecurityTokenService.class, features);
    }

}
