
package org.oasis_open.docs.ws_sx.ws_trust._200512.wsdl;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.0-SNAPSHOT
 * 2011-01-06T10:25:02.244+02:00
 * Generated source version: 2.4.0-SNAPSHOT
 * 
 */
 
public class SecurityTokenService_SecurityTokenServiceSOAP_Server{

    protected SecurityTokenService_SecurityTokenServiceSOAP_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new SecurityTokenServiceImpl();
        String address = "http://localhost:18080/SecurityTokenServiceProvider/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new SecurityTokenService_SecurityTokenServiceSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
