
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.oasis_open.docs.ws_sx.ws_trust._200512.wsdl;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue Dec 28 16:52:06 EET 2010
 * Generated source version: 2.3.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SecurityTokenServiceProvider",
                      portName = "SecurityTokenServiceSOAP",
                      targetNamespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl/",
                      wsdlLocation = "file:/D:/WORK_SOPERA/ws-trust/ws-trust-1.4.wsdl",
                      endpointInterface = "org.oasis_open.docs.ws_sx.ws_trust._200512.wsdl.SecurityTokenResponseService")
                      
public class SecurityTokenResponseServiceImpl implements SecurityTokenResponseService {

    private static final Logger LOG = Logger.getLogger(SecurityTokenResponseServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.oasis_open.docs.ws_sx.ws_trust._200512.wsdl.SecurityTokenResponseService#requestSecurityTokenResponse(org.oasis_open.docs.ws_sx.ws_trust._200512.RequestSecurityTokenResponseType  response )*
     */
    public void requestSecurityTokenResponse(org.oasis_open.docs.ws_sx.ws_trust._200512.RequestSecurityTokenResponseType response) { 
        LOG.info("Executing operation requestSecurityTokenResponse");
        System.out.println(response);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
