<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GreeterImplService" targetNamespace="http://talend.org/esb/examples/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://talend.org/esb/examples/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://talend.org/esb/examples/" schemaLocation="greeterimpl_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="greetMe">
    <wsdl:part name="parameters" element="tns:greetMe">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="greetMeResponse">
    <wsdl:part name="parameters" element="tns:greetMeResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Greeter">
    <wsdl:operation name="greetMe">
      <wsdl:input name="greetMe" message="tns:greetMe">
    </wsdl:input>
      <wsdl:output name="greetMeResponse" message="tns:greetMeResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="GreeterImplServiceSoapBinding" type="tns:Greeter">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="greetMe">
      <soap:operation soapAction="urn:GreetMe" style="document"/>
      <wsdl:input name="greetMe">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="greetMeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GreeterImplService">
    <wsdl:port name="GreeterImplPort" binding="tns:GreeterImplServiceSoapBinding">
      <soap:address location="http://localhost:8080/locator-sample-tomcat/services/GreeterImplPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
